import os
from dotenv import load_dotenv
from Database.database_loader import DatabaseLoader
from Helpers.apply_user_preferences import apply_user_preferences
from Penalty.evaluator import Evaluator
from Algorithms.spea2_optimizer import run_spea2

# Load environment variables from .env file
load_dotenv()

# Initialize the DB loader
db = DatabaseLoader()

# 1. Load the master list of foods ONCE
master_foods = db.load_foods()

# 2. Process User 1
user1 = db.load_user(user_id=1)
user1_foods = apply_user_preferences(master_foods, user1)
# -> Now you pass user1_foods and user1 into the DietDecoder and MOEA!

# 3. Process User 2
user2 = db.load_user(user_id=2)
user2_foods = apply_user_preferences(master_foods, user2)
# -> Now you pass user2_foods and user2 into the DietDecoder and MOEA!

# ----------- Output - Çalışıyor mu diye bakmak için, istersen yorum satırı yapabilirsin. -----------
print(f"✅ Successfully loaded {len(master_foods)} foods from the database!")

print(f"\n--- USER 1 INFO ---")
print(f"Vegetarian? {user1.is_vegetarian}")
print(f"Energy Limits (RLL, RUL): {user1.dri_limits.get('Energy')}")
print(f"Number of custom preferences: {len(user1.food_preferences)}")

print(f"\n--- USER 2 INFO ---")
print(f"Vegetarian? {user2.is_vegetarian}")
print(f"Protein Limits (RLL, RUL): {user2.dri_limits.get('Protein')}")

# --- EVALUATOR TEST SCRIPT ---
print("\n--- PENALTY EVALUATOR TEST ---")

# 1. Initialize the Evaluator (Starting with lambda = 1.0)
evaluator = Evaluator(lambda_weight=1.0)

# 2. Simulate a "bad" menu generated by the algorithm.
# Let's pretend the algorithm picked a menu that is way too low in Energy, 
# but way too high in Sodium.
mock_menu_totals = {
    'Energy': 1200.0,       # Likely under the RLL (Under-nutrition)
    'Protein': 85.0,        # Likely within normal range
    'Carbohydrate': 150.0,  # Might be slightly under
    'Fiber': 30.0,          # Likely normal
    'Sodium (Na)': 3500.0   # Way over the RUL (Over-nutrition)
}

print("Simulated Menu Totals:")
for nutrient, amount in mock_menu_totals.items():
    print(f"  - {nutrient}: {amount}")

# 3. Fetch the real DRI limits for User 1 that you loaded from the DB
print("\nUser 1 Real DRI Limits (RLL, RUL):")
for nutrient, limits in user1.dri_limits.items():
    print(f"  - {nutrient}: {limits}")

# 4. Run the Evaluator!
penalty_score = evaluator.calculate_penalty(mock_menu_totals, user1.dri_limits)

# 5. Display the results
print("\n--- TEST RESULTS ---")
print(f"Total Penalty (R): {penalty_score:.4f}")

# Example of how this affects the fitness score:
fake_raw_preference = 200.0
penalized_fitness = fake_raw_preference - (evaluator.lambda_weight * penalty_score)

print(f"Fake Raw Preference Score: {fake_raw_preference}")
print(f"Final Penalized Fitness:   {penalized_fitness:.4f}")
print("---------------------------------\n")


#AKİF ŞENYİĞİT



# ... (main.py içerisindeki Evaluator test scriptinin bitişinden sonrası) ...

print("\n==========================================")
print("     SPEA2 OPTİMİZASYON AŞAMASI           ")
print("==========================================")

# Gerçek bir Evaluator nesnesi oluştur
main_evaluator = Evaluator(lambda_weight=1.0)

# KULLANICI 1 İÇİN ÇALIŞTIR (Non-Vegetarian)
res_user1 = run_spea2(user1, user1_foods, main_evaluator, pop_size=50, n_gen=50)

print(f"\n✅ Kullanıcı 1 İçin İşlem Tamamlandı!")
print(f"Bulunan Pareto Çözüm Sayısı: {len(res_user1.F) if res_user1.F is not None else 0}")

# KULLANICI 2 İÇİN ÇALIŞTIR (Vegetarian)
res_user2 = run_spea2(user2, user2_foods, main_evaluator, pop_size=50, n_gen=50)

print(f"\n✅ Kullanıcı 2 İçin İşlem Tamamlandı!")
print(f"Bulunan Pareto Çözüm Sayısı: {len(res_user2.F) if res_user2.F is not None else 0}")

# (7. kişi res_user1.F ve res_user1.X verilerini alıp CSV'ye dökecek ve görselleri hazırlayacak.)